// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwu65KczIzhQSpL77dEjvZYAsPH5FSMhQ',
    appId: '1:168426970446:web:a9678abeb1e4e1be16d21f',
    messagingSenderId: '168426970446',
    projectId: 'auth-noor',
    authDomain: 'auth-noor.firebaseapp.com',
    storageBucket: 'auth-noor.firebasestorage.app',
    measurementId: 'G-M288YP5CZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDjKmbEGj2sM_2BfPAoUdnAZflFcKSKeg',
    appId: '1:168426970446:android:76492d8fb79e047916d21f',
    messagingSenderId: '168426970446',
    projectId: 'auth-noor',
    storageBucket: 'auth-noor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1aMpi7iGQe1WC68caLxw-UqutoBhArU',
    appId: '1:168426970446:ios:5d847d81ab73121f16d21f',
    messagingSenderId: '168426970446',
    projectId: 'auth-noor',
    storageBucket: 'auth-noor.firebasestorage.app',
    iosBundleId: 'com.auth.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1aMpi7iGQe1WC68caLxw-UqutoBhArU',
    appId: '1:168426970446:ios:003aaf9eadc5d20916d21f',
    messagingSenderId: '168426970446',
    projectId: 'auth-noor',
    storageBucket: 'auth-noor.firebasestorage.app',
    iosBundleId: 'com.example.loea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwu65KczIzhQSpL77dEjvZYAsPH5FSMhQ',
    appId: '1:168426970446:web:997ae56c5f9885f416d21f',
    messagingSenderId: '168426970446',
    projectId: 'auth-noor',
    authDomain: 'auth-noor.firebaseapp.com',
    storageBucket: 'auth-noor.firebasestorage.app',
    measurementId: 'G-PHFZLCGTMV',
  );
}
